.TH LC-GO 1 "January 2025" "Coherent UNIX" "User Commands"
.SH NAME
lc-go - list directory contents in columnar format

.SH SYNOPSIS
.B lc-go
[\fB-1Fabcdfp\fR] [\fIDIRECTORY\fR]...

.SH DESCRIPTION
.B lc-go
lists the contents of the specified
.IR DIRECTORY ,
or the current directory if none is provided. It categorizes files by type (e.g., regular files, directories) and displays them in columns for readability. By default, filenames are printed in color based on their type. Color output can be disabled by setting the environment variable NO_COLOR=1.

.SH OPTIONS
.TP
.BR -1
List one file per line, instead of in columns.
.TP
.B -F
Enable file type indicators after filenames, like "*" after executable files.
.TP
.B -a
List all files, including hidden entries "." and "..".
.TP
.B -b
List block-special files only.
.TP
.B -c
List character-special files only.
.TP
.B -d
List directories only.
.TP
.B -f
List regular files only.
.TP
.B -l
List symbolic links only.
.TP
.B -p
List pipe (FIFO) files only.

.SH USAGE
Options can be combined for customized output. For example, to display all files, one per line:
.PP
.RS
.EX
lc-go \-a1
.EE
.RE

.PP
If no directory is specified,
.B lc-go
defaults to the current working directory.

.SH EXAMPLES
The following command lists all regular files in the current directory:
.PP
.RS
.EX
lc-go -f
.EE
.RE

.SH SEE ALSO
.BR lc (1)
.BR ls (1)
